name = "edge-proxy"
type = "webpack"
account_id = "dc56444c4c955a1653106ccf997c1067"
workers_dev = true
compatibility_date = "2025-05-20"
main = "index.js"

vars = { ENDPOINT = "https://dev-hasura.ithaa.net/v1/graphql" }

